import type { Metadata } from "next";
import { Overlock_SC } from "next/font/google";

import "./globals.css";

const overlock = Overlock_SC({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${overlock.className}`}>
      <body>{children}
      </body>
    </html>
  );
}
